### PR TITLE
Remove dependency on use-context-selector

### LINKED ISSUE #2322: Module not found: Error: Can't resolve 'use-context-selector'
# Bug Reports

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/)

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

victory-core/es/victory-state seems recently to have added a dependence on `use-context-selector` without expressing this dependence in its package.json. As a result, webpack builds now fail.

Further complicating matters... the latest several versions of `use-context-selector` depend on `react >= 18`... so I'm not even sure how you all would express a dependence on this node module in a way that allowed for that kind of flexibility. oof. 

of note, patternfly, which uses you, is not yet react 18, and yet they express a `^` floating dependence on you that brings in this breaking change!

Full error message:
> Module not found: Error: Can't resolve 'use-context-selector' in '.../node_modules/victory-core/es/victory-state'

The fix, for react 17 users, is `npm install use-context-selector@1.1`; >1.1 have a react >= 18 dependence

### Reproduction

todo

### PR DESCRIPTION
**Pull request by becca-bailey**
This removes our dependency on use-context-selector in favor of vanilla context. Once we have a more fully-featured re-write, we can do some performance comparisons and measure whether something like `use-context-selector` provides noticeable performance gains, and reconsider introducing something similar. 

Fixes #2322

### CODE REVIEW

**Review by gksander — APPROVED** [review]
ezpz

File: packages/victory-core/src/victory-state/victory-provider.tsx [hunk 1]
```diff
@@ -81,17 +81,12 @@ export function VictoryProvider({
...
-        "useVictoryContext must be used within a VictoryProvider",
-      );
-    }
-    return selector(context);
-  });
+  const context = useContext(VictoryContext);
+  if (!context) {
+    throw new Error("useVictoryContext must be used within a VictoryProvider");
+  }
+  return selector(context);
```
Comment (scottrippey) [inline packages/victory-core/src/victory-state/victory-provider.tsx:89]: Well that was surprisingly easy :)

**Review by scottrippey — APPROVED** [review]

File: packages/victory-core/src/victory-state/victory-provider.tsx (hunk 1 above)
Comment (becca-bailey) [reply packages/victory-core/src/victory-state/victory-provider.tsx:89]: Abstraction for the win!
