### PR TITLE
Bugfix: Calculated domains respect custom baselines 

### LINKED ISSUE #1123: Calculated domains in VictoryArea are not respecting custom baselines
Domains always include zero even if the y0 value is set in data.

Latest (broken):
https://codesandbox.io/s/q7n6r44yq6

Working in 0.26.1:
https://codesandbox.io/s/mqpx3rmkk8

### PR DESCRIPTION
**Pull request by cullenjett**
Fixes #1123 

The `<VictoryArea />` and `<VictoryBar />` components rely on the `Domain.getDomainWithZero()` function to calculate their domain ranges. There was a regression introduced in version 0.27.0 where that function stopped respecting custom baseline domains via `data.y0` values and instead always set the minimum domain to 0.

### CODE REVIEW

File: packages/victory-core/src/victory-util/domain.js [hunk 1]
```diff
@@ -289,23 +289,38 @@ function getDomainWithZero(props, axis) {
   if (propsDomain) {
     return propsDomain;
   }
+
+  const dataset = Data.getData(props);
+  const y0Initial = dataset && dataset[0] ? dataset[0]._y0 : 0;
+  const y0Min = dataset.reduce((min, datum) => {
```
Comment (boygirl) [inline packages/victory-core/src/victory-util/domain.js]: Is there a reason for calculating `y0Initial` rather than using `Infinity` as the initial value in this reduce?

File: packages/victory-core/src/victory-util/domain.js [hunk 2]
```diff
@@ -289,23 +289,38 @@ function getDomainWithZero(props, axis) {
...
     }
-    const defaultMin = minDomain || 0;
-    const defaultMax = maxDomain || 0;
-    const min = minDomain !== undefined ? minDomain : Collection.getMinValue(domain, defaultMin);
-    const max = maxDomain !== undefined ? maxDomain : Collection.getMaxValue(domain, defaultMax);
+
+    const defaultMin = y0Min !== undefined ? y0Min : 0;
+    const maxDomainProp = getMaxFromProps(props, axis);
+    const minDomainProp = getMinFromProps(props, axis);
+    const max = maxDomainProp !== undefined ? maxDomainProp : Collection.getMaxValue(domain, 0);
```
Comment (boygirl) [inline packages/victory-core/src/victory-util/domain.js]: I think this needs to be `Collection.getMaxValue(domain, defaultMin)` for the situation where all the y / y0 values are negative

Comment (boygirl) [inline packages/victory-core/src/victory-util/domain.js]: I think this needs to be `Collection.getMaxValue(domain, defaultMin)` for the situation where all the `y` and `y0` values are negative

**Comment by cullenjett** [comment]
@boygirl good catch on the max domain value. I made the change and added a test for it
