### PR TITLE
fix for 'Candlestick labels show incorrect midpoint label'

### LINKED ISSUE #2923: Candlestick labels show incorrect midpoint label
When setting the `labels` property to `true`, candlestick charts incorrectly show the value `true` as a midpoint label, but should show no midpoint label.

Image

<details>
<summary>Example Code</summary>

```
<VictoryChart
  domainPadding={{ x: 25 }}
  theme={VictoryTheme.clean}
>
  <VictoryCandlestick
    labels
    data={[
      {
        x: "3/1/23",
        open: 5,
        close: 10,
        high: 15,
        low: 0,
      },
      {
        x: "3/2/23",
        open: 10,
        close: 15,
        high: 20,
        low: 5,
      },
      {
        x: "3/3/23",
        open: 15,
        close: 20,
        high: 22,
        low: 10,
      },
      {
        x: "3/4/23",
        open: 20,
        close: 10,
        high: 25,
        low: 7,
      },
      {
        x: "3/5/23",
        open: 10,
        close: 8,
        high: 15,
        low: 5,
      },
    ]}
  />
</VictoryChart>
```
</details>

### PR DESCRIPTION
**Pull request by nstolpe**
### Description

Adds a check for a boolean value in label text and does not return a label component if that is the case.

Fixes #2923

### CODE REVIEW

File: packages/victory-candlestick/src/victory-candlestick.tsx [hunk 1]
```diff
@@ -28,7 +28,7 @@ export interface VictoryCandlestickStyleInterface {
   data?: VictoryStyleObject;
   high?: VictoryStyleObject;
   highLabels?: VictoryLabelStyleObject | VictoryLabelStyleObject[];
-  labels?: VictoryLabelStyleObject | VictoryLabelStyleObject[];
+  labels?: VictoryLabelStyleObject | VictoryLabelStyleObject[] | boolean;
```
Comment (nstolpe) [inline packages/victory-candlestick/src/victory-candlestick.tsx:31]: I don't think this change is necessary, as the label isn't expecting a boolean anywhere else in the code, but leaving it here until review in case there is a desire use case that I'm unfamiliar with.

Comment (carbonrobot) [reply packages/victory-candlestick/src/victory-candlestick.tsx:31]: Correct, this change isn't needed. This interface is for styling the chart, the `labels` property actually comes from `VictoryMultiLabelableProps`.

**Review by carbonrobot — APPROVED** [review]
